### ISSUE TITLE
 The game crashed when entering the chapter 7

### ISSUE THREAD

**Issue by DemoJameson** [EverestAPI/CelesteTAS-EverestInterop#1]
Ver 1.2.1.7 [Everest: 0.0.353-travis-6f39e]
	2018-04-02 00:43:24
	System.FieldAccessException: 方法“TAS.Manager.UpdateInputs()”尝试访问字段“Celeste.SummitVignette.ready”失败。
	   在 TAS.Manager.UpdateInputs()
	   在 TAS.EverestInterop.CelesteTASModule.MInput_Update() 位置 D:\Repos\CelesteTAS-EverestInterop\CelesteTAS-EverestInterop\CelesteTASModule.cs:行号 271
	   在 Monocle.Engine.Update(GameTime gameTime)
	   在 trampoline_Update_orig(Engine , GameTime )
	   在 TAS.EverestInterop.CelesteTASModule.Engine_Update(Engine self, GameTime gameTime) 位置 D:\Repos\CelesteTAS-EverestInterop\CelesteTAS-EverestInterop\CelesteTASModule.cs:行号 256
	   在 Celeste.Celeste.Update(GameTime gameTime)
	   在 Microsoft.Xna.Framework.Game.Tick()
	   在 Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
	   在 Microsoft.Xna.Framework.GameHost.OnIdle()
	   在 Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
	   在 Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
	   在 System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
	   在 System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
	   在 System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
	   在 System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
	   在 System.Windows.Forms.Application.Run(Form mainForm)
	   在 Microsoft.Xna.Framework.WindowsGameHost.Run()
	   在 Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
	   在 Monocle.Engine.RunWithLogging()

**Comment by 0x0ade** [comment]
I've completely forgot that CelesteTAS has been updated. I'll update the EverestInterop mod later today. Thank you for reporting this!

**Comment by 0x0ade** [comment]
Can you please test this version before I add it as a release?

[CelesteTAS-EverestInterop.zip](https://github.com/EverestAPI/CelesteTAS-EverestInterop/files/1868132/CelesteTAS-EverestInterop.zip)

**Comment by DemoJameson** [comment]
It works perfect, thanks!

**Comment by 0x0ade** [comment]
Great, thanks for reporting back so quickly :D
