### ISSUE TITLE
Unix Rtc is only written to after the game closes.

### ISSUE THREAD

**Issue by Apppppppple** [EverestAPI/CelesteTAS-EverestInterop#19]
I could never get the rtc pipe to work so I tried to mess around and figure out why. It looks like the pipe is getting output, but it isn't viewable until the game closes. Repro steps: Launch celeste and run `tail -f /tmp/celestetas`. Start a tas and no output should appear. Upon closing the game a bunch of messages should show up at once.

**Comment by DemoJameson** [comment]
The `Unix Rtc` feature seems to never work properly

If on Linux or macOS, check the working TAS file path in the `Mod Options -> Enabled` menu item, edit it with your favorite text editor, and enable `Info HUD` to show the auxiliary information
