### ISSUE TITLE
Feature Request: Horizontally Centerer Camera

### ISSUE THREAD

**Issue by LozenChen** [EverestAPI/CelesteTAS-EverestInterop#55]
这个特性的用意如下:
一方面水平居中足以让 TASer 观察到绝大部分所需的信息,
另一方面竖直不居中, 这样就可以避免看到关卡上下边界以外的部分, 保持了一定的观赏性.

例: 横向高速TAS, 比如 Ultra jump 9A, 试了下效果不错.

因为实现很简单, 而唯一的问题是具体如何设计相应的开关, 所以就不开 PR 了.

**Comment by DemoJameson** [comment]
https://github.com/EverestAPI/CelesteTAS-EverestInterop/commit/fe9e94bc4cdf230600c6ed7843157e15df5f96d6
