### ISSUE TITLE
Show hitboxes not working

### ISSUE THREAD

**Issue by Magnus1001** [EverestAPI/CelesteTAS-EverestInterop#72]
When I press ctrl + N with the mod installed, the hitboxes don't show up. Also, the hotkey for showing hitboxes does not even appear.

**Comment by psyGamer** [comment]
Ctrl+N toggles simplified graphics, not hitboxes. The hotkey for hitboxes is Ctrl+B by default. If that doesnt work, check your keybindings. Note that they are key-combos, not multiple keys.
Since this issue is quite old already, ill close this as stale if there isnt a resonse in 14 days
