### ISSUE TITLE
Feature: Move Info HUD to another position when player covers it

### ISSUE THREAD

**Issue by mekb-turtle** [EverestAPI/CelesteTAS-EverestInterop#89]
If the opacity is too low, the Info HUD can be hard to read. If it's too high, the player can be hard to see. It'd be nice if we could specify two positions and the Info HUD would move between them.

**Comment by psyGamer** [comment]
I feel like that could become visually jarring if its jumping around? If you use center camera, the player should never cover the Info HUD.
