### ISSUE TITLE
Upload studio releases automatically to GameBanana

### ISSUE THREAD

**Issue by WEGFan** [EverestAPI/CelesteTAS-EverestInterop#92]
Currently, studio executable is downloaded in-game, but in China mainland the connection speed to GitHub is very unstable, causing it very hard to download. I'd like to make mirrors of release files and maybe integrate to CelesteTAS (using the download mirror setting in Everest), but they are not on GameBanana, otherwise my work is a lot easier since I'm already mirroring all files on GameBanana. I'll be appreciated if it's possible to upload studio releases via GitHub actions to GameBanana.

**Comment by WEGFan** [comment]
Or maybe make studio a mod per platform, so we can also auto update studio ingame, CelesteTAS can add optional dependencies to ensure studio version is correct.

**Comment by psyGamer** [comment]
I feel like Studio being its own mod would cause more issues than it solves.
Uploading Studio builds to gamebanana would be possible, but i would prefer not to.
How viable would it be for you that the release action posts the builds to your mirror? Idk your setup so thats a bit hard to judge

**Comment by psyGamer** [comment]
Mirroring the github releases would work, yeah

**Comment by psyGamer** [comment]
Any updates on this?

**Comment by WEGFan** [comment]
Still working on it, once I'm done I'll open another issue here.
